### PR TITLE
2020 11 27 new tables

### PR DESCRIPTION
**Pull request by nschairer**
# Description of change
Added customers v3 as well as customers attribute-values

# Manual QA steps
 - 
Ran through our BigQuery target and verified data
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by melizeche** [comment]
This would be a nice to have, any chance that this PR get reviewed? I don't know who is in charge of that, maybe @luandy64 ?

**Comment by nschairer** [comment]
> This would be a nice to have, any chance that this PR get reviewed? I don't know who is in charge of that, maybe @luandy64 ?

I have reached out to @timvisher as well

**Comment by cosimon** [comment]
Hi @nschairer 

Can you share logs demonstrating that the tap has been tested locally with the changes and that it functions as expected?

**Comment by nschairer** [comment]
Here is a log from just now, I ran it locally against our dev environment after adding a new order and a new customer:

INFO BigCommerce API Authorized.
INFO Starting discover
INFO Finished discover
INFO BigCommerce API Authorized.
INFO products: Starting sync
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 1, "tags": {"endpoint": "products"}}
INFO products: Completed sync (1 rows)
INFO coupons: Skipping - not selected
INFO customers: Skipping - not selected
INFO orders: Starting sync
WARNING Removed 7 paths during transforms:
        customer_locale
        products.0.name_customer
        products.0.name_merchant
        products.0.upc
        products.0.variant_id
        store_default_currency_code
        store_default_to_transactional_exchange_rate
WARNING Removed paths list: ['customer_locale', 'products.0.name_customer', 'products.0.name_merchant', 'products.0.upc', 'products.0.variant_id', 'store_default_currency_code', 'store_default_to_transactional_exchange_rate']
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 1, "tags": {"endpoint": "orders"}}
INFO orders: Completed sync (1 rows)
INFO attributevalues: Starting sync
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 16, "tags": {"endpoint": "attributevalues"}}
INFO attributevalues: Completed sync (16 rows)
INFO customersv3: Starting sync
WARNING Removed 1 paths during transforms:
        form_fields
WARNING Removed paths list: ['form_fields']
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 1, "tags": {"endpoint": "customersv3"}}
INFO customersv3: Completed sync (1 rows)
INFO Finished sync

**Review by leslievandemark — APPROVED** [review]

**Comment by leslievandemark** [comment]
Hi @nschairer,

We released your PR, but unfortunately had to roll it back because it resulted in this error:
`Error saving discovered stream customersv3: {"status":"BadRequest","message":"Invalid streams specification","errors":["Invalid type '#{\"type-integer.json\"}'"]}`

There seems to be an issue with the use of references in the `customersv3` schema. If you would like to test and submit and new pr with out schema references we move forward and re-release. Thanks again for your contribution.

**Pull request merged**
